name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    permissions:
      contents: read
    uses: alterioncorp/.github/.github/workflows/reusable-build.yml@main
    with:
      mvn-goal: clean deploy -U -Ppublish
      setup-gpg: true
    secrets: inherit
