name: Build

on:
  push:
    branches-ignore: [main]

jobs:
  build:
    uses: alexlitovsky-dev/.github/.github/workflows/reusable-build.yml@main
    with:
      mvn-goal: clean verify -U
    secrets: inherit
