name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    uses: alexlitovsky-dev/.github/.github/workflows/reusable-build.yml@main
    with:
      mvn-goal: clean deploy -U
      sign: true
    secrets: inherit
