name: Build

on:
  push:
    branches-ignore: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - uses: alterioncorp/.github/.github/actions/maven-settings@main

      - name: Build
        run: mvn clean verify -U
