name: Build

on:
  push:
    branches-ignore: [develop, main]

jobs:
  build:
    uses: alexlitovsky/.github/.github/workflows/reusable-build.yml@main
    with:
      mvn-goal: clean verify -U
    secrets: inherit
